name: Preview Deploy to gh-pages per PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Pages workspace
        run: |
          mkdir -p site
          cp -R . site/

      - name: Checkout gh-pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin gh-pages || true
          git checkout -B gh-pages origin/gh-pages || git checkout -b gh-pages
          mkdir -p preview/pr-${{ github.event.pull_request.number }}
          rm -rf preview/pr-${{ github.event.pull_request.number }}/*
          cp -R site/* preview/pr-${{ github.event.pull_request.number }}/
          touch .nojekyll
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "PR #${{ github.event.pull_request.number }} preview update"
            git push origin gh-pages
          fi

      - name: Compute Preview URL
        id: url
        run: |
          echo "value=https://loiche94.github.io/LM-SERVICES/preview/pr-${{ github.event.pull_request.number }}/" >> $GITHUB_OUTPUT

      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = "${{ steps.url.outputs.value }}";
            const prNumber = context.issue.number;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            const marker = "[preview-url-marker]";
            const body = `## Aperçu de la PR\n\n${marker}\nAperçu disponible ici : ${previewUrl}\n\n- L'URL reste stable pendant toute la durée de vie de la PR\n- Le contenu est mis à jour automatiquement à chaque commit`;
            const existing = comments.find(c => c.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body
              });
            }

  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          PREVIEW_DIR="preview/pr-${{ github.event.pull_request.number }}"
          if [ -d "$PREVIEW_DIR" ]; then
            rm -rf "$PREVIEW_DIR"
            git add -A
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}"
            git push origin gh-pages
          fi
